#ifndef EXPERIMENTAL_MODE_H
#define EXPERIMENTAL_MODE_H

#define EXPERIMENTAL_MODE_NO_RTS 0
#if EXPERIMENTAL_MODE_NO_RTS == 1
    #define EXPERIMENTAL_MODE_KEEP_ALL_KEYS 1
#else
    #define EXPERIMENTAL_MODE_KEEP_ALL_KEYS 0
#endif

#endif