#ifndef EXPERIMENTAL_MODE_H
#define EXPERIMENTAL_MODE_H

#define EXPERIMENTAL_MODE_KEEP_ALL_KEYS 0
#define EXPERIMENTAL_MODE_NO_RTS 0
#if EXPERIMENTAL_MODE_NO_RTS == 1
    #undef EXPERIMENTAL_MODE_KEEP_ALL_KEYS
    #define EXPERIMENTAL_MODE_KEEP_ALL_KEYS 1
#endif
#define EXPERIMENTAL_MODE_USE_ICEBERG_FOR_LOCK_TABLE 1
#endif
